# Generated by Django 5.1.1 on 2024-09-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tourismplace_tourismplaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaccountdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
