# Generated by Django 5.1.1 on 2024-09-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tourismplace_duration_tourismplace_places_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tourismplace',
            name='places_count',
            field=models.IntegerField(null=True),
        ),
    ]
