# Generated by Django 5.1.1 on 2024-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tourismplace_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='duration',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tourismplace',
            name='places_count',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
