# Generated by Django 5.1.1 on 2024-09-24 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_accounts_type_alter_user_gender_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 9, 51, 53, 509024, tzinfo=datetime.timezone.utc)),
        ),
    ]
