# Generated by Django 4.2.11 on 2024-09-26 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_comment_rating_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 15, 13, 41, 573907, tzinfo=datetime.timezone.utc)),
        ),
    ]
