# Generated by Django 5.1.1 on 2024-09-30 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_comment_rating_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temporaryaccountdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
