# Generated by Django 5.1.1 on 2024-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismplace',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
